#Конфигурация плагина Display

#Каждые n секунд обновляется текст на объектах. 0 - вообще не обновлять. Тип - int
textUpdateInterval: 1

#Сообщения
#Используйте {prefix} для префикса перед сообщением
#Используйте {help} для команды показа помощи
#Используйте {subcommands} для списка действий команды (указаны в help)
#Используйте {type} для указания типа объекта
#Используйте {types} для списка типов display сущностей
#Используйте {id} и {newid} для указания id объекта
#Используйте {x}, {y}, {z} и {world} для координат и мира
messages:
  prefix: "<#6d6d6d>[<gradient:#fdd134:#fb630e>Display</gradient><#6d6d6d>]<reset>"
  errors:
    onlyPlayer: "<red>Команду может выполнять только игрок!"
    notFull: "{prefix} <red>Неполная команда! Список команд: {help}"
    unknownAction: "{prefix} <red>Неизвестный тип действия! Используйте: {subcommands}"
    tooManyArguments: "{prefix} <red>Слишком много аргументов!"
    noPermission: "{prefix} <red>У вас нет прав на выполнение данной команды!"
    notFoundObjectType: "{prefix} <red>Не найден тип объекта! Используйте: {types}"
    unknownObjectType: "{prefix} <red>Неизвестный тип объекта! Используйте: {types}"
    notFoundId: "{prefix} <red>Не найден ID объекта!"
    invalidId: "{prefix} <red>ID объекта должен быть числом!"
    idAlreadyInUse: "{prefix} <red>ID {id} уже используется!"
    idDoesNotExist: "{prefix} <red>Объекта с ID {id} не существует!"
    notFoundEditType: "{prefix} <red>Не найден тип редактирования! Используйте: {types}"
    unknownEditType: "{prefix} <red>Неизвестный тип редактирования! Используйте: {types}"
    notFoundBlock: "{prefix} <red>Не найден тип блока!"
    unknownBlock: "{prefix} <red>Неизвестный блок!"
    notFoundItem: "{prefix} <red>Не найден тип предмета!"
    unknownItem: "{prefix} <red>Неизвестный предмет!"
    notFoundLineNumber: "{prefix} <red>Не найден номер строки!"
    invalidLineNumber: "{prefix} <red>Номер строки должен быть числом!"
    unknownLineNumber: "{prefix} <red>Неизвестная строка!"
    oneLine: "{prefix} <red>Осталась последняя строка!"
    notFoundText: "{prefix} <red>Не найден текст!"
    notFoundScales: "{prefix} <red>Не найдены размеры!"
    invalidScales: "{prefix} <red>Неверный формат размеров!"
    notFoundDimension: "{prefix} <red>Не найдено измерение! Используйте: {types}"
    unknownDimension: "{prefix} <red>Неизвестное измерение! Используйте: {types}"
    notFoundCoords: "{prefix} <red>Не найдены координаты!"
    invalidCoords: "{prefix} <red>Неверный формат координат!"
  successfully:
    reloaded: "{prefix} <green>Конфиг плагина успешно перезагружен!"
    created: "{prefix} <green>Объект для отображения с ID {id} и типом {type} успешно создан!"
    deleted: "{prefix} <green>Объект с ID {id} успешно удалён!"
    edited: "{prefix} <green>У объекта с ID {id} успешно изменён параметр {edittype} на {value}<green>!"
    editedScale: "{prefix} <green>У объекта с ID {id} успешно изменён размер на {scalex}, {scaley}, {scalez}"
    editedAddline: "{prefix} <green>Объекту с ID {id} успешно добавлена строка под номером {linenumber} с значением {text}<reset><green>!"
    editedSetline: "{prefix} <green>У объекта с ID {id} успешно изменена строка под номером {linenumber} на значение {text}<reset><green>!"
    editedRemoveline: "{prefix} <green>У объекта с ID {id} успешно удалена строка под номером {linenumber}<reset><green>!"
    teleportedCoords: "{prefix} <green>Объект с ID {id} успешно перемещён на координаты {x} {y} {z} в мире {world}!"
    teleportedHere: "{prefix} <green>Объект с ID {id} успешно перемещён на ваши координаты!"
    teleportedTo: "{prefix} <green>Вы были успешно перемещены на координаты объекта с ID {id}!"
    changedID: "{prefix} <green>У объекта с ID {id} ID был изменен на {newid}!"