#Конфигурация плагина Display

#Сообщения
#Используйте {prefix} для префикса перед сообщением
#Используйте {help} для команды показа помощи
#Используйте {subcommands} для списка действий команды (указаны в help)
#Используйте {types} для списка типов display сущностей
#Используйте {id} для указания id объекта
#Используйте {x}, {y}, {z}, {world} для координат и мира
messages:
  prefix: "&#6d6d6d[&#fdd134D&#fdbf2ei&#fcac27s&#fc9a21p&#fc881bl&#fb7514a&#fb630ey&#6d6d6d]&r"
  errors:
    onlyPlayerConsole: "&cКоманду может выполнять только игрок!"
    notFull: "{prefix} &cНеполная команда! Список команд: {help}"
    unknownAction: "{prefix} &cНеизвестный тип действия! Используйте: {subcommands}"
    tooManyArguments: "{prefix} &cСлишком много аргументов!"
    notFoundObjectType: "{prefix} &cНе найден тип объекта! Используйте: {types}"
    unknownObjectType: "{prefix} &cНеизвестный тип объекта! Используйте: {types}"
    notFoundId: "{prefix} &cНе найден ID объекта!"
    invalidId: "{prefix} &cID объекта должен быть числом!"
    idAlreadyInUse: "{prefix} &cID {id} уже используется!"
    idDoesNotExist: "{prefix} &cОбъекта с ID {id} не существует!"
    notFoundEditType: "{prefix} &cНе найден тип редактирования! Используйте: {types}"
    unknownEditType: "{prefix} &cНеизвестный тип редактирования! Используйте: {types}"
    notFoundBlock: "{prefix} &cНе найден тип блока!"
    unknownBlock: "{prefix} &cНеизвестный блок!"
    notFoundItem: "{prefix} &cНе найден тип предмета!"
    unknownItem: "{prefix} &cНеизвестный предмет!"
    notFoundDimension: "{prefix} &cНе найдено измерение! Используйте: {types}"
    unknownDimension: "{prefix} &cНеизвестное измерение! Используйте: {types}"
    notFoundCoords: "{prefix} &cНе найдены координаты!"
    invalidCoords: "{prefix} &cНеверный формат координат!"
  successfully:
    created: "{prefix} &aОбъект для отображения с ID {id} успешно создан!"
    deleted: "{prefix} &aОбъект с ID {id} успешно удалён!"
    edited: "{prefix} &aУ объекта с ID {id} успешно изменён параметр {edittype} на {value}!"
    teleportedCoords: "{prefix} &aОбъект с ID {id} успешно перемещён на координаты {x} {y} {z} в мире {world}!"
    teleportedHere: "{prefix} &aОбъект с ID {id} успешно перемещён на ваши координаты!"
    teleportedTo: "{prefix} &aВы были успешно перемещены на координаты объекта с ID {id}!"
    changedID: "{prefix} &aУ объекта с ID {id} ID был изменен на {newid}!"