name: Display
version: 1.8
main: me.itzisonn_.display.DisplayPlugin
api-version: 1.19
softdepend: [PlaceholderAPI, ProtocolLib]
author: ItzIsonn_
description: 'Interaction with display entities'

commands:
  display: {}

permissions:
  display.*:
    children:
      display.help: true
      display.reload: true
      display.create: true
      display.load: true
      display.delete: true
      display.list: true
      display.edit: true
      display.tp: true
  display.help: {}
  display.reload: {}
  display.create: {}
  display.load: {}
  display.delete: {}
  display.list: {}
  display.edit: {}
  display.tp: {}