name: Display
version: 1.1
main: me.itzisonn_.display.Display
api-version: 1.19
author: ItzIsonn_
description: 'Взаимодействие с сущностями display'

commands:
  display:
    description: Главная команда плагина