###---------------------------###
###----------DISPLAY----------###
###---------ItzIsonn_---------###
###---------------------------###

#Каждые n тиков обновляется текст на объектах. 0 - вообще не обновлять. Тип - int
textUpdateInterval: 20

#Сообщения
#Используйте {prefix} для префикса перед сообщением
#Используйте {id} для указания id объекта
messages:
  prefix: "<gradient:#adf3fd:#e173fd>Display</gradient> <#6d6d6d>|<reset>"
  errors:
    onlyPlayer: "<red>Команду может выполнять только игрок!"
    noPermission: "{prefix} <red>У вас нет прав на выполнение данной команды!"
    notFull: "{prefix} <red>Неполная команда! Список команд: /display help"
    unknownAction: "{prefix} <red>Неизвестный тип действия!"
    tooManyArguments: "{prefix} <red>Слишком много аргументов!"
    notFoundId: "{prefix} <red>Не найден ID объекта!"
    invalidId: "{prefix} <red>ID объекта должен быть числом!"
    idAlreadyInUse: "{prefix} <red>Этот ID уже используется!"
    idDoesNotExist: "{prefix} <red>Объекта с этим ID не существует!"
    notFoundObjectType: "{prefix} <red>Не найден тип объекта!"
    unknownObjectType: "{prefix} <red>Неизвестный тип объекта!"
    notFoundEditFormat: "{prefix} <red>Не найден формат редактирования!"
    invalidEditFormat: "{prefix} <red>Ошибка в формате редактирования!"
    notFoundTeleportType: "{prefix} <red>Не найден тип телепорта!"
    unknownTeleportType: "{prefix} <red>Неизвестный тип телепорта!"
    notFoundDimension: "{prefix} <red>Не найдено измерение!"
    unknownDimension: "{prefix} <red>Неизвестное измерение!"
    notFoundCoords: "{prefix} <red>Не найдены координаты!"
    invalidCoords: "{prefix} <red>Неверный формат координат!"
  successfully:
    reloaded: "{prefix} <green>Конфиг плагина успешно перезагружен!"
    created: "{prefix} <green>Новый объект для отображения с ID {id} успешно создан!"
    deleted:
      id: "{prefix} <green>Объект с ID {id} успешно удалён!"
      all: "{prefix} <green>Все объекты успешно удалёны!"
    edited: "{prefix} <green>Объект с ID {id} успешно отредактирован!"
    teleported:
      pos: "{prefix} <green>Объект с ID {id} успешно перемещён!"
      here: "{prefix} <green>Объект с ID {id} успешно перемещён!"
      to: "{prefix} <green>Вы успешно переместились к объекту с ID {id}!"
    cloned: "{prefix} <green>Объект с ID {id} успешно клонирован!"